# Shadowrocket: 2026-06-11 21:37:38
[General]
fallback-dns-server = https://1.1.1.1/dns-query,https://8.8.8.8/dns-query,system

# DoH 加密 DNS
dns-server = https://cloudflare-dns.com/dns-query,https://dns.google/dns-query,https://dns.alidns.com/dns-query,system

# DoH 异常时使用系统 DNS 兜底

# 跳过系统代理
bypass-system = true

# 局域网直连
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com

# 排除运营商/内网网段
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.168.0.0/16, 224.0.0.0/4, 255.255.255.255/32, 239.255.255.250/32

# IPv6
ipv6 = true
prefer-ipv6 = false

# DNS 设置
dns-fallback-system = false
dns-direct-system = true
dns-direct-fallback-proxy = false

# 网络兼容
icmp-auto-reply = true
always-reject-url-rewrite = false

# 允许私有 IP 返回
private-ip-answer = true

[Proxy Group]

# 全直连
AI-PROXY = select, DIRECT

[Rule]
########## 🪧 屏蔽谷歌营销广告 ##########
DOMAIN,googleads.g.doubleclick.net,REJECT

# 所有流量直连
FINAL,DIRECT

[Host]
localhost = 127.0.0.1
